[package]
name = "ws-client-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee-ws-client = { version = "=0.2.0-alpha.7" }
tokio = {"version"= "0.2", features=["rt-threaded", "macros"]}